### ISSUE TITLE
Nodos crashes when a non-image file is loaded into the ReadImage node.

### ISSUE THREAD

**Issue by zduturan** [nodos-dev/workspace#16]
Steps:
- Add ReadImage node.
- Connect to the Ajaout or Sink node
- Load a non-image file (tested with mp4 and zip)
- Nodos crashes.
- Expectation: Node shall fail gracefully

Nodos: 1.2.0.b3536
Jira: R5-735

**Comment by fcturan20** [comment]
Fixed in [this commit](https://github.com/nodos-dev/modules/commit/e1ab2cf07fca29341e244a56684d86ba6a3cd90c)
