### ISSUE TITLE
Graph causes Nodos engine to crash when it has Input/Output pin from Actor that is specific for that UE project

### ISSUE THREAD

**Issue by zduturan** [nodos-dev/workspace#17]
Contact: @seckin

When a property of an Actor which is specific for launched project shows as a input/output pin on the the if this graph launch with different project which has not that actor in it makes engine crash. Even the showed input/ouput pin shows as property again, it makes engine crash. To crash happen pipeline should be running

Portal pins might cause the problem:

![image](https://github.com/user-attachments/assets/ce532122-f93f-454f-97aa-933fc4101cac)

Steps:
- Launch a UE project
- Add UE process node to graph
- Add User Track Node and Sink Node
- Spawn Reality Camera 
- Connect User track to track pin on the Process Node
- Connect Scene pin to sink node
- In Process node select a actor specific for that project and show as input of its property
- Save the graph and close the project 
- Launch different project which has not that actor in it 
- Load the saved graph
- Expected:
- Graph loaded and created input pin of that actor shows as orphan 

Used Graph: 
- [demo_baked_ue.zip](https://github.com/user-attachments/files/17403038/demo_baked_ue.zip)

This graph has user track, UE process node and sink node. UE process node is Demo project which we used for our tests. Inside of it there is screenTwoRight in Blueprints folder in that video texture property shows as input then shows as property again. After tried to open this graph for different project Nodos engine crashes.

Reality: 5.4.SP2.0794
Nodos: 1.2.0b3586
Jira: R5-770

**Comment by fcturan20** [comment]
Fixed in [v1.2.0.b3608](https://github.com/mediaz/nodos/releases/tag/v1.2.0.b3608)

**Comment by zduturan** [comment]
This issue has a note **"Fixed in v1.2.0.b3608"** and also it has "help wanted"/"cannot reproduce" labels. 

How can we help about the reproduction?

**Comment by caner-milko** [comment]
I think we made a mistake with the issue labels, it should be fixed in [v1.2.0.b3608](https://github.com/mediaz/nodos/releases/tag/v1.2.0.b3608) so it should be ready to test.
