### ISSUE TITLE
After reloading the graph, the projection cube rotation values open with different values than those saved

### ISSUE THREAD

**Issue by zduturan** [nodos-dev/workspace#5]
Nodos version: 1.2.0.b3334

- Go to UE5 node and select projection cube actor.
- Change the rotation values of transform properties.
- Save the graph.
- Clear the graph.
- Open the saved graph.

**Expected**: Values should be same after loading graph.
**Actual**: After reloading the graph, the projection cube rotation values open with different values than those saved.

**Note:** Please check the attached video for the exact reproduction steps

- OldLink: https://github.com/zerodensity/test/issues/283
- Screen recording: https://github.com/user-attachments/assets/5a596c66-d459-4738-9ce9-fd34e72c2084
- Internal tag: R5-680

**Comment by zduturan** [comment]
This is still failing with the latest Nodos bundle 3564

**Comment by candhyan** [comment]
@ugurtur please check out https://youtu.be/LOo9s0VjepM

**Comment by zduturan** [comment]
Closing - working as intended.
